### ISSUE TITLE
ContextFreeGrammar.generate() can't choose a random item from a set

### ISSUE THREAD

**Issue by gbspend** [twinters/gitta#1]
ContextFreeGrammar.generate() causes a TypeError because it's trying to call random.choice on a `set` at line 174

![Screenshot from 2021-10-22 17-30-17](https://user-images.githubusercontent.com/3513552/138533173-2b7bef15-bb07-4631-ac91-cb3f6126396f.png)

Looks like you'll need to change line 173 of context_free_grammar.py to make "possibilities" into a `list` or something so that you can randomly draw from it.

Here's a StackOverflow thread for reference: https://stackoverflow.com/questions/15837729/random-choice-from-set-python

**Comment by twinters** [comment]
Thanks for letting me know! I've pushed a fix for this in the most recent commit.
Sorry it took so long!
